stages:
  - build
    #- test
  - deploy
  - revert
  
variables:
  docker_html_path: "/var/www"
  env: prod
  deploy_subfolder: html


# install build $env prod React App
install_dependencies:
  image: node:14.15.0-stretch
  stage: build
  script:
    - yarn install
    - yarn build
    - mv build build_$env
  artifacts:
    paths:
      - node_modules
      - build_$env
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules

test:
  stage: deploy
  tags:
    - stagshell  
  script:
    - cp -r build /www/test-app/$CI_COMMIT_SHA
    #- cp -Pv /www/html /www/test-app/$CI_COMMIT_SHA/prev-version
    - cp -Pv $docker_html_path/staging/master  
    - ln -fsnv /var/www/test-app/$CI_COMMIT_SHA /$docker_html_path/staging/master  
  allow_failure: true

build_staging:
  # передаем переменную от stage: build
  extends: install_dependencies
  variables:
    env: staging
    #Создание переменной для staging и настройка проекта React React App переменной % REACT_APP_WEBSITE_PREFIX% 
    REACT_APP_WEBSITE_PREFIX: "[staging]"
    PUBLIC_URL: "/$CI_COMMIT_BRANCH"

deploy_staging:
  extends: deploy_prod
  tags:
    - stagshell 
  variables:
    deploy_subfolder: staging/$CI_COMMIT_BRANCH
    env: staging
  when: always
  #make mistakes
  allow_failure: true
  only:
    - master
    - /feature-.*/

deploy_prod:
  stage: deploy
  script:
    - cp -r build_$env $docker_html_path/test-app/${env}_$CI_COMMIT_SHA
      #ссылка на предыдущую папку, который ссылался раньше на /var/www/html (предыдущая версия)
      #- cp -Pv $docker_html_path/$deploy_subfolder $docker_html_path/test-app/${env}_$CI_COMMIT_SHA/prev-version || true
      #copy folder
    - ln -fsnv $docker_html_path/test-app/${env}_$CI_COMMIT_BEFORE_SHA $docker_html_path/test-app/${env}_$CI_COMMIT_SHA/prev-version || true
  only:
    - master
#switching the active version
activate_staging:
  extends: activate_prod
  variables:
    deploy_subfolder: staging/$CI_COMMIT_BRANCH
    env: staging
  when: always
  only:
    - master
    - /feature-.*/

activate_prod:
  stage: deploy
  tags:
    - stagshell 
  script:
    - ln -fsnv /var/www/test-app/${env}_$CI_COMMIT_SHA $docker_html_path/$deploy_subfolder
  when: manual
  only:
    - master
  
  
#revert:
#  stage: revert
#  tags:
#    - stagshell
#  when: manual
#  script:
          #- cp -Pv --remove-destination /www/test-app/$CI_COMMIT_SHA/prev-version /www/html  
##    - rm $docker_html_path/$deploy_subfolder  
    #- cp -Pv --remove-destination $docker_html_path/test-app/${env}_$CI_COMMIT_BEFORE_SHA/prev-version $docker_html_path/html
##    - cp -Pv --remove-destination $docker_html_path/test-app/${env}_$CI_COMMIT_BEFORE_SHA/prev-version $docker_html_path/staging/master

revert_previous_two:
  stage: revert
  tags:
    - stagshell
  when: manual
  script:
    - rm $docker_html_path/$deploy_subfolder
      # Поcле удаления симлинка происходит копирование из симлинка где лежит предредудушая версия копируем в var/www/html     
    - cp -Pv $docker_html_path/test-app/${env}_$CI_COMMIT_BEFORE_SHA${env}_$CI_COMMIT_BEFORE_SHA/pvev-version $docker_html_path/$deploy_subfolder 
 #
